global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'blackbox-task-3-ex-2'
    metrics_path: /probe
    static_configs:
      - targets:
        - https://watchlist-95637.azurewebsites.net/Movies/Watched

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target

      - source_labels: [__param_target]
        target_label: instance

      - target_label: __address__
        replacement: 127.0.0.1:9115

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093

rule_files:
  - "alert.rules.yml"
